### PR TITLE
Add test dependencies to setup py and simplify travis again

### PR DESCRIPTION
**Pull request by znicholls**
@andrewgsavage this should be the last of my fiddling

### CODE REVIEW

**Comment by andrewgsavage** [comment]
OK will leave you to it!

You should get to 3.5 failing, 3.6 3.7 passing. Not tried 2.7

**Comment by andrewgsavage** [comment]
https://travis-ci.com/andrewgsavage/pint-pandas/builds/97452605

**Comment by znicholls** [comment]
> https://travis-ci.com/andrewgsavage/pint-pandas/builds/97452605

Nice. It looks like that failure is just about index order so can be fixed by making the test index order dependent. I'll have a go at fixing that as part of this.

**Comment by andrewgsavage** [comment]
Yea I'm setting up an 3.5 env to confirm that atm

**Comment by andrewgsavage** [comment]
wooo that works. Is there anything else you want to do here?

**Comment by znicholls** [comment]
> Is there anything else you want to do here?

Nope :)

**Pull request merged**
